# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JokeMeUp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JokeMeUp
  pod 'Alamofire', '~> 4.6'
  pod "PromiseKit", "~> 6.0"
  pod 'Google-Mobile-Ads-SDK'

end
